package banco

import org.springframework.jdbc.core.JdbcTemplate

class Query (private val jdbcTemplate: JdbcTemplate) {

    fun createTable() {
        jdbcTemplate.execute("""
        create table IF NOT EXISTS Leitura(
        idLeitura int GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        fkTotem int,
        cpuPercent decimal(5,2),
        diskPercent decimal(5,2),
        ramPercent decimal(5,2),
        mbUpload decimal(7,3),
        mbDownload decimal(7,3),
        horario char(8),
        dia char(10)
        );
    """)
    }

    fun insert(valores:MutableList<String>) {
        jdbcTemplate.update("""
            insert into Leitura (fkTotem, cpuPercent, diskPercent, ramPercent, horario, dia) values
            (?, ?, ?, ?, ?, ?)
        """, valores[0], valores[1], valores[2], valores[3], valores[4], valores[5])
    }
}